default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] || "localhost" %>
  username: <%= ENV["POSTGRES_USER"] || Rails.application.credentials.postgresql[:user] %>
  password: <%= ENV["POSTGRES_PASSWORD"] || Rails.application.credentials.postgresql[:password] %>

development:
  <<: *default
  database: findoc_development

test:
  <<: *default
  database: findoc_test

production:
  <<: *default
  database: findoc_production
  username: findoc
  password: <%= ENV['FINDOC_DATABASE_PASSWORD'] %>
